---
enable_dashboard: yes
listen_port: 3005
hide_logs: no
node_down_alert_minutes: 3
prometheus_enabled: yes
prometheus_listen_port: 28686
pagerduty:
  enabled: no
  api_key: aaaaaaaaaaaabbbbbbbbbbbbbcccccccccccc
  default_severity: alert
discord:
  enabled: no
  webhook: https://discord.com/api/webhooks/999999999999999999/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
telegram:
  enabled: no
  api_key: '5114361364:AAFP01UqFwlYWJFVGuaaES7XI1OUJktYHeg'
  channel: "-542022627"
chains:
  "Osmosis":
    chain_id: osmosis-1
    valoper_address: osmovaloper1083svrca4t350mphfv9x45wq9asrs60c6rv0j5
    public_fallback: no
    alerts:
      stalled_enabled: yes
      stalled_minutes: 10
      consecutive_enabled: yes
      consecutive_missed: 5
      consecutive_priority: critical
      percentage_enabled: no
      percentage_missed: 10
      percentage_priority: warning
      alert_if_inactive: yes
      alert_if_no_servers: yes
      pagerduty:
        enabled: yes
        api_key: "" # uses default if blank
      discord:
        enabled: no
        webhook: "" # uses default if blank
      telegram:
        enabled: no
        api_key: "" # uses default if blank
        channel: "" # uses default if blank
    nodes:
      - url: https://rpc-osmosis-ia.cosmosia.notional.ventures
        alert_if_down: no
  "CosmosHub":
    chain_id: cosmoshub-4
    valoper_address: cosmosvaloper1083svrca4t350mphfv9x45wq9asrs60cdmrflj
    public_fallback: no
    alerts:
      stalled_enabled: yes
      stalled_minutes: 10
      consecutive_enabled: yes
      consecutive_missed: 5
      consecutive_priority: critical
      percentage_enabled: no
      percentage_missed: 10
      percentage_priority: warning
      alert_if_inactive: yes
      alert_if_no_servers: yes
      pagerduty:
        enabled: yes
        api_key: "" # uses default if blank
      discord:
        enabled: yes
        webhook: "" # uses default if blank
      telegram:
        enabled: yes
        api_key: "" # uses default if blank
        channel: "" # uses default if blank
    nodes:
      - url: https://rpc-cosmoshub-ia.cosmosia.notional.ventures/
        alert_if_down: yes
      - url: https://some-other-node:443
        alert_if_down: no
  "Juno":
    chain_id: juno-1
    valoper_address: junovaloper1083svrca4t350mphfv9x45wq9asrs60cpqzg0y
    public_fallback: no
    alerts:
      stalled_enabled: yes
      stalled_minutes: 10
      consecutive_enabled: yes
      consecutive_missed: 5
      consecutive_priority: critical
      percentage_enabled: no
      percentage_missed: 10
      percentage_priority: warning
      alert_if_inactive: yes
      alert_if_no_servers: yes
      pagerduty:
        enabled: yes
        api_key: "" # uses default if blank
      discord:
        enabled: yes
        webhook: "" # uses default if blank
      telegram:
        enabled: yes
        api_key: "" # uses default if blank
        channel: "" # uses default if blank
    nodes:
      - url: https://rpc-juno-ia.cosmosia.notional.ventures/
        alert_if_down: yes
      - url: https://some-other-node:443
        alert_if_down: no
   "Sifchain":
    chain_id: Sifchain-1
    valoper_address: sifvaloper1083svrca4t350mphfv9x45wq9asrs60cyssqu6
    public_fallback: no
    alerts:
      stalled_enabled: yes
      stalled_minutes: 10
      consecutive_enabled: yes
      consecutive_missed: 5
      consecutive_priority: critical
      percentage_enabled: no
      percentage_missed: 10
      percentage_priority: warning
      alert_if_inactive: yes
      alert_if_no_servers: yes
      pagerduty:
        enabled: yes
        api_key: "" # uses default if blank
      discord:
        enabled: yes
        webhook: "" # uses default if blank
      telegram:
        enabled: yes
        api_key: "" # uses default if blank
        channel: "" # uses default if blank
    nodes:
      - url: https://rpc-sifchain-ia.cosmosia.notional.ventures/
        alert_if_down: yes
      - url: https://some-other-node:443
        alert_if_down: no
